### PR TITLE
Add .travis.yml to run unit tests on Travis CI

### PR DESCRIPTION
**Pull request by ppinard**
One question is how to obtain the test data required to run all the tests?

### CODE REVIEW

**Comment by drix00** [comment]
The test data files were added using git LFS in the last commit on the master branch: 1d6991a520524ed5b923d000d6e9202768accf7b
You can update your branch and see if Travis can use git LFS. All tests were OK on my computer.

**Comment by ppinard** [comment]
One problem I found with running tests with LFS data is that GitHub has a bandwidth limit for LFS data. Free projects only have [1 GB of bandwidth per month](https://help.github.com/articles/about-storage-and-bandwidth-usage/#bandwidth-quota). I check if we could only pull the LFS data on pull requests and releases.

**Comment by drix00** [comment]
Does Travis support git-lfs? It seem that it does not and that you have to install it in the before_install in the .travis.yml. Any way, we will need to update the test for the test_Data files as they only check if the file exist. Without git-lfs, the file exist but contain a pointer to the git-lfs file.

**Comment by ppinard** [comment]
> Does Travis support git-lfs?

We need to install git-lfs manually. I followed the example here when I did it: https://github.com/travis-ci/travis-ci/issues/3634#issuecomment-220554067

> we will need to update the test for the test_Data files as they only check if the file exist. Without git-lfs, the file exist but contain a pointer to the git-lfs file.

All tests are passing right now even without git-lfs. See https://travis-ci.org/ppinard/pycasinotools. 155 tests were skipped.

**Comment by drix00** [comment]
You need to merge the master branch from drix00/pycasinotools with your ppinard/pycasinotools travis branch. Right now you don't have the test_data folder on it. 

The 155 tests skipped is OK (without the folder).
Currently the test is as follow, but with the dummy git-lfs file it will pass and raise an error when the test try to open the file.

```python
if not os.path.isfile(filepath):
    raise SkipTest
```
I will try to look at the git-lfs documentation on the format of the file to detect it.

**Comment by drix00** [comment]
The last commits on master implement a test for git-lfs file and absence of test_data file. See commits af82eafa9ad780a4d269a11f79809117031619da and b15ecfba66be103f74cf5ababbe17c7cca50917e.
I have test it with 

- git-lfs installed (all tests pass)
- git-lfs not installed (some tests skipped)
- without the test_data folder (some tests skipped)

So it should work with Travis without git-lfs installed.

As a note, DON'T add dummy git-lfs file in the git repository, that completely block pushing the local commit.

**Comment by ppinard** [comment]
@drix00 you seem to have a `.travis.yml` in the root directory. This pull request is no longer needed.

**Pull request closed without merging**
